### ISSUE TITLE
I can't build this project using cmake in windows system.

### ISSUE THREAD

**Issue by jeremywrightkim** [griegler/handpose#2]
I tried to build this project using cmake spend much times.
I built "rv_utils" then build "handpose" project. 
And then I got a *.sln visual studio projects. 
But It isn't work. 
To build this project in windows system is to hard.
What are the additional library requirements?
Can you help me?

**Comment by griegler** [comment]
The code was never intended to run also on Windows. Though, it might be possible, as all libraries are available on Windows as well. 
I am sorry that I can not help you, but I also do not have a Windows machine to test it myself.

**Comment by jeremywrightkim** [comment]
Thx for your reply.
I'll try to build another method.
